<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW Capacitance CDATA #IMPLIED>
  <!ATTLIST ROW Case CDATA #IMPLIED>
  <!ATTLIST ROW Case_EIA CDATA #IMPLIED>
  <!ATTLIST ROW Case_Metric CDATA #IMPLIED>
  <!ATTLIST ROW Category CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Code_IPC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEDEC CDATA #IMPLIED>
  <!ATTLIST ROW Color CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW Component_Type CDATA #IMPLIED>
  <!ATTLIST ROW ComponentHeight CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL CDATA #IMPLIED>
  <!ATTLIST ROW Count CDATA #IMPLIED>
  <!ATTLIST ROW CreateDate CDATA #IMPLIED>
  <!ATTLIST ROW Current CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW Database_Table_Name CDATA #IMPLIED>
  <!ATTLIST ROW DataSheet CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetVersion CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Frequency CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW HelpURL CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_2 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_3 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_4 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_5 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_6 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_7 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_8 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_9 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_2 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_3 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_4 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_5 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_6 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_7 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_8 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_9 CDATA #IMPLIED>
  <!ATTLIST ROW Material CDATA #IMPLIED>
  <!ATTLIST ROW Max_Thickness CDATA #IMPLIED>
  <!ATTLIST ROW Mfg CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Model_PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Simulation CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Mounted CDATA #IMPLIED>
  <!ATTLIST ROW Mounting_Technology CDATA #IMPLIED>
  <!ATTLIST ROW Mounting_Type CDATA #IMPLIED>
  <!ATTLIST ROW Operating_Temperature CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW Package___Case CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PackageVersion CDATA #IMPLIED>
  <!ATTLIST ROW Packaging CDATA #IMPLIED>
  <!ATTLIST ROW Part_Description CDATA #IMPLIED>
  <!ATTLIST ROW Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW PartNumber CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pin_Count CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Polarity CDATA #IMPLIED>
  <!ATTLIST ROW Power CDATA #IMPLIED>
  <!ATTLIST ROW Precision CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Rated_Voltage CDATA #IMPLIED>
  <!ATTLIST ROW Ratings CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW RoHS CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SCDType CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SMD CDATA #IMPLIED>
  <!ATTLIST ROW SMD_DIP CDATA #IMPLIED>
  <!ATTLIST ROW Socket CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Supplier CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_9 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_9 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_9 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_9 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_9 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_9 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_2 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_3 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_4 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_5 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_6 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_7 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_8 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_9 CDATA #IMPLIED>
  <!ATTLIST ROW Table1 CDATA #IMPLIED>
  <!ATTLIST ROW TC CDATA #IMPLIED>
  <!ATTLIST ROW Technology CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW Tolerance CDATA #IMPLIED>
  <!ATTLIST ROW Type CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
  <!ATTLIST ROW Voltage___Supply CDATA #IMPLIED>
  <!ATTLIST ROW ______ CDATA #IMPLIED>
  <!ATTLIST ROW _________ CDATA #IMPLIED>
  <!ATTLIST ROW ________ CDATA #IMPLIED>
  <!ATTLIST ROW _ CDATA #IMPLIED>
  <!ATTLIST ROW _ID_ CDATA #IMPLIED>
  <!ATTLIST ROW _PARENTID_ CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber" Caption="Application_BuildNumber" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="Capacitance" Caption="Capacitance" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Case" Caption="Case" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Case_EIA" Caption="Case-EIA" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Case_Metric" Caption="Case-Metric" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Category" Caption="Category" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="Code_IPC" Caption="Code_IPC" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="Code_JEDEC" Caption="Code_JEDEC" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="Color" Caption="Color" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="Component_Type" Caption="Component Type" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="ComponentHeight" Caption="ComponentHeight" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description" Caption="ComponentLink1Description" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL" Caption="ComponentLink1URL" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description" Caption="ComponentLink2Description" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL" Caption="ComponentLink2URL" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="Count" Caption="Count" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="CreateDate" Caption="CreateDate" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Current" Caption="Current" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Database_Table_Name" Caption="Database Table Name" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="DataSheet" Caption="DataSheet" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="DatasheetVersion" Caption="DatasheetVersion" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="Frequency" Caption="Frequency" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="HelpURL" Caption="HelpURL" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer" Caption="Manufacturer" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_1" Caption="Manufacturer 1" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_2" Caption="Manufacturer 2" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_3" Caption="Manufacturer 3" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_4" Caption="Manufacturer 4" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_5" Caption="Manufacturer 5" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_6" Caption="Manufacturer 6" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_7" Caption="Manufacturer 7" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_8" Caption="Manufacturer 8" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_9" Caption="Manufacturer 9" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number" Caption="Manufacturer Part Number" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_1" Caption="Manufacturer Part Number 1" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_2" Caption="Manufacturer Part Number 2" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_3" Caption="Manufacturer Part Number 3" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_4" Caption="Manufacturer Part Number 4" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_5" Caption="Manufacturer Part Number 5" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_6" Caption="Manufacturer Part Number 6" Index="79" BandIndex="0" RowIndex="0" ColIndex="79" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_7" Caption="Manufacturer Part Number 7" Index="80" BandIndex="0" RowIndex="0" ColIndex="80" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_8" Caption="Manufacturer Part Number 8" Index="81" BandIndex="0" RowIndex="0" ColIndex="81" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_9" Caption="Manufacturer Part Number 9" Index="82" BandIndex="0" RowIndex="0" ColIndex="82" Width="100"></COLUMN>
    <COLUMN Name="Material" Caption="Material" Index="83" BandIndex="0" RowIndex="0" ColIndex="83" Width="100"></COLUMN>
    <COLUMN Name="Max_Thickness" Caption="Max Thickness" Index="84" BandIndex="0" RowIndex="0" ColIndex="84" Width="100"></COLUMN>
    <COLUMN Name="Mfg" Caption="Mfg" Index="85" BandIndex="0" RowIndex="0" ColIndex="85" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="86" BandIndex="0" RowIndex="0" ColIndex="86" Width="100"></COLUMN>
    <COLUMN Name="Model_PCB3D" Caption="Model:PCB3D" Index="87" BandIndex="0" RowIndex="0" ColIndex="87" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity" Caption="Model:Signal Integrity" Index="88" BandIndex="0" RowIndex="0" ColIndex="88" Width="100"></COLUMN>
    <COLUMN Name="Model_Simulation" Caption="Model:Simulation" Index="89" BandIndex="0" RowIndex="0" ColIndex="89" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="90" BandIndex="0" RowIndex="0" ColIndex="90" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="91" BandIndex="0" RowIndex="0" ColIndex="91" Width="100"></COLUMN>
    <COLUMN Name="Mounted" Caption="Mounted" Index="92" BandIndex="0" RowIndex="0" ColIndex="92" Width="100"></COLUMN>
    <COLUMN Name="Mounting_Technology" Caption="Mounting Technology" Index="93" BandIndex="0" RowIndex="0" ColIndex="93" Width="100"></COLUMN>
    <COLUMN Name="Mounting_Type" Caption="Mounting Type" Index="94" BandIndex="0" RowIndex="0" ColIndex="94" Width="100"></COLUMN>
    <COLUMN Name="Operating_Temperature" Caption="Operating Temperature" Index="95" BandIndex="0" RowIndex="0" ColIndex="95" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="96" BandIndex="0" RowIndex="0" ColIndex="96" Width="100"></COLUMN>
    <COLUMN Name="Package___Case" Caption="Package / Case" Index="97" BandIndex="0" RowIndex="0" ColIndex="97" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="98" BandIndex="0" RowIndex="0" ColIndex="98" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="99" BandIndex="0" RowIndex="0" ColIndex="99" Width="100"></COLUMN>
    <COLUMN Name="PackageVersion" Caption="PackageVersion" Index="100" BandIndex="0" RowIndex="0" ColIndex="100" Width="100"></COLUMN>
    <COLUMN Name="Packaging" Caption="Packaging" Index="101" BandIndex="0" RowIndex="0" ColIndex="101" Width="100"></COLUMN>
    <COLUMN Name="Part_Description" Caption="Part Description" Index="102" BandIndex="0" RowIndex="0" ColIndex="102" Width="100"></COLUMN>
    <COLUMN Name="Part_Number" Caption="Part Number" Index="103" BandIndex="0" RowIndex="0" ColIndex="103" Width="100"></COLUMN>
    <COLUMN Name="PartNumber" Caption="PartNumber" Index="104" BandIndex="0" RowIndex="0" ColIndex="104" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="105" BandIndex="0" RowIndex="0" ColIndex="105" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="106" BandIndex="0" RowIndex="0" ColIndex="106" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="107" BandIndex="0" RowIndex="0" ColIndex="107" Width="100"></COLUMN>
    <COLUMN Name="Pin_Count" Caption="Pin Count" Index="108" BandIndex="0" RowIndex="0" ColIndex="108" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="109" BandIndex="0" RowIndex="0" ColIndex="109" Width="100"></COLUMN>
    <COLUMN Name="Polarity" Caption="Polarity" Index="110" BandIndex="0" RowIndex="0" ColIndex="110" Width="100"></COLUMN>
    <COLUMN Name="Power" Caption="Power" Index="111" BandIndex="0" RowIndex="0" ColIndex="111" Width="100"></COLUMN>
    <COLUMN Name="Precision" Caption="Precision" Index="112" BandIndex="0" RowIndex="0" ColIndex="112" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="113" BandIndex="0" RowIndex="0" ColIndex="113" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="114" BandIndex="0" RowIndex="0" ColIndex="114" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="115" BandIndex="0" RowIndex="0" ColIndex="115" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="116" BandIndex="0" RowIndex="0" ColIndex="116" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="117" BandIndex="0" RowIndex="0" ColIndex="117" Width="100"></COLUMN>
    <COLUMN Name="Rated_Voltage" Caption="Rated Voltage" Index="118" BandIndex="0" RowIndex="0" ColIndex="118" Width="100"></COLUMN>
    <COLUMN Name="Ratings" Caption="Ratings" Index="119" BandIndex="0" RowIndex="0" ColIndex="119" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="120" BandIndex="0" RowIndex="0" ColIndex="120" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="121" BandIndex="0" RowIndex="0" ColIndex="121" Width="100"></COLUMN>
    <COLUMN Name="RoHS" Caption="RoHS" Index="122" BandIndex="0" RowIndex="0" ColIndex="122" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="123" BandIndex="0" RowIndex="0" ColIndex="123" Width="100"></COLUMN>
    <COLUMN Name="SCDType" Caption="SCDType" Index="124" BandIndex="0" RowIndex="0" ColIndex="124" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="125" BandIndex="0" RowIndex="0" ColIndex="125" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="126" BandIndex="0" RowIndex="0" ColIndex="126" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="127" BandIndex="0" RowIndex="0" ColIndex="127" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="128" BandIndex="0" RowIndex="0" ColIndex="128" Width="100"></COLUMN>
    <COLUMN Name="SMD" Caption="SMD" Index="129" BandIndex="0" RowIndex="0" ColIndex="129" Width="100"></COLUMN>
    <COLUMN Name="SMD_DIP" Caption="SMD_DIP" Index="130" BandIndex="0" RowIndex="0" ColIndex="130" Width="100"></COLUMN>
    <COLUMN Name="Socket" Caption="Socket" Index="131" BandIndex="0" RowIndex="0" ColIndex="131" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="132" BandIndex="0" RowIndex="0" ColIndex="132" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="133" BandIndex="0" RowIndex="0" ColIndex="133" Width="100"></COLUMN>
    <COLUMN Name="Supplier" Caption="Supplier" Index="134" BandIndex="0" RowIndex="0" ColIndex="134" Width="100"></COLUMN>
    <COLUMN Name="Supplier_1" Caption="Supplier 1" Index="135" BandIndex="0" RowIndex="0" ColIndex="135" Width="100"></COLUMN>
    <COLUMN Name="Supplier_2" Caption="Supplier 2" Index="136" BandIndex="0" RowIndex="0" ColIndex="136" Width="100"></COLUMN>
    <COLUMN Name="Supplier_3" Caption="Supplier 3" Index="137" BandIndex="0" RowIndex="0" ColIndex="137" Width="100"></COLUMN>
    <COLUMN Name="Supplier_4" Caption="Supplier 4" Index="138" BandIndex="0" RowIndex="0" ColIndex="138" Width="100"></COLUMN>
    <COLUMN Name="Supplier_5" Caption="Supplier 5" Index="139" BandIndex="0" RowIndex="0" ColIndex="139" Width="100"></COLUMN>
    <COLUMN Name="Supplier_6" Caption="Supplier 6" Index="140" BandIndex="0" RowIndex="0" ColIndex="140" Width="100"></COLUMN>
    <COLUMN Name="Supplier_7" Caption="Supplier 7" Index="141" BandIndex="0" RowIndex="0" ColIndex="141" Width="100"></COLUMN>
    <COLUMN Name="Supplier_8" Caption="Supplier 8" Index="142" BandIndex="0" RowIndex="0" ColIndex="142" Width="100"></COLUMN>
    <COLUMN Name="Supplier_9" Caption="Supplier 9" Index="143" BandIndex="0" RowIndex="0" ColIndex="143" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Currency_1" Caption="Supplier Currency 1" Index="144" BandIndex="0" RowIndex="0" ColIndex="144" Width="100"></COLUMN>